# Generated by Django 4.0.2 on 2022-02-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField()),
                ('Created_by', models.DateField(null=True)),
            ],
        ),
    ]
