# Generated by Django 4.0.2 on 2022-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Created_by',
            field=models.DateField(auto_now_add=True),
        ),
    ]
